name: Bug report 
 description: Create a report to help us improve (search for duplicates first) 
 labels: bug 
 body: 
  - type: textarea 
    attributes: 
     label: Issue description 
     description: Explain clearly and unambiguously what went wrong 
     placeholder: Tell us here about the bug/problem 
    validations: 
     required: true 
  - type: textarea 
    attributes: 
     label: How to reproduce this issue? 
     description: Try to explain what you did for the bug to occur. A good explanation of steps to reproduce helps us locate the bug faster. If applicable, add screenshots to help explain your problem. 
     placeholder: | 
       Step 1: ... 
       Step 2: ... 
       ... 
    validations: 
      required: true 
  - type: dropdown 
    attributes: 
     label: Operating system 
     description: Which operating system do you use with MCreator? 
     options: 
      - Windows 
      - macOS 
      - Linux 
      - Other (Tell us at the Specifications part) 
    validations: 
      required: true 
  - type: textarea 
    attributes: 
     label: Details 
     description: To understand the issue, we need some details of your setup & system 
     placeholder: | 
       MCreator version: [2022.2] 
       Generator type: [forge-1.18.2/forge-1.16.5] 
    validations: 
      required: true 
  - type: textarea 
    attributes: 
     label: Example workspace 
     description: | 
       If the bug is related to the workspace, always provide a minimal reproducible example workspace, export it to a shareable ZIP file, and attach it to the ticket. 
        
       Keep in mind your workspace of the project is not minimal reproducible example. Make a workspace only with elements crucial for the bug. 
        
       Drag the file into this area. 
     placeholder: Insert here 
    validations: 
     required: false 
  - type: textarea 
    attributes: 
     label: Logs 
     description: | 
       If applicable, include game or build logs (full logs, do not crop them, in text format, screenshots of logs are not acceptable) from the Console tab or terminal and steps to reproduce the bug in your workspace. 
        
       Longer logs should be posted on [GitHub Gists](https://gist.github.com/) (or other paste service) and linked here. 
     placeholder: https://gist.github.com/... 
    validations: 
     required: false
