name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - azzy380
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Generator version
      description: Which generator are you using?
      options:
     		- Forge 1.20.1
        - Forge 1.19.4
        - Forge 1.19.2
        - Forge 1.18.2
        - NeoForge 1.20.1
    validations:
      required: true
  - type: textarea
    id: mcreator
    attributes:
      label: MCreator version
      description: Which version of MCreator are you using. 
    validations:
      required: true
  - type: textarea
    id: workspace
    attributes:
      label: Example Workspace (optional)
      description: If the bug is related to the workspace, always provide a minimal reproducible example workspace, export it to a shareable ZIP file, and attach it to the ticket. Keep in mind your workspace of the project is not minimal reproducible example. Make a workspace only with elements crucial for the bug. Drag the file into this area. 
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output (optional)
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
