name: Feature Request
description: File a feature request
title: "[Feature Request]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: request
    attributes:
      label: Whats the request? 
      description: Is your feature request related to a problem? Please describe. A clear and concise description of what the problem and/or idea is. 
      placeholder: I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Example Workspace (optional)
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: extras
    attributes:
      label: Additional context (optional)
      description: Add any other context or screenshots about the feature request here.
